version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    env_file:
      - ./docker_api.env
  postgres:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - ./docker_db.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
